// Document Report Generator (Text Format)

import { AnalysisResult } from '@/types';
import { getEthTrustLevelDefinition } from './ethtrust';

export function generateTextReport(result: AnalysisResult): void {
  let report = '';

  // Header
  report += '═══════════════════════════════════════════════════════════\n';
  report += '     SMART CONTRACT SECURITY ANALYSIS REPORT\n';
  report += '═══════════════════════════════════════════════════════════\n\n';

  // Contract Information
  report += 'CONTRACT INFORMATION\n';
  report += '───────────────────────────────────────────────────────────\n';
  report += `File Name:        ${result.fileName}\n`;
  report += `Analysis Date:    ${new Date(result.timestamp).toLocaleString()}\n`;
  report += `Analysis ID:      ${result.analysisId}\n`;
  report += `Analysis Time:    ${(result.analysisTime / 1000).toFixed(2)} seconds\n\n`;

  // Summary Metrics
  report += 'SECURITY SUMMARY\n';
  report += '───────────────────────────────────────────────────────────\n';
  report += `Security Score:   ${result.securityScore}/100\n`;
  report += `Risk Level:       ${result.riskLevel}\n`;
  report += `EthTrust Level:   ${result.ethTrustLevel}/5\n`;
  report += `Total Issues:     ${result.statistics.total}\n\n`;

  // Vulnerability Statistics
  report += 'VULNERABILITY BREAKDOWN\n';
  report += '───────────────────────────────────────────────────────────\n';
  report += `Critical:         ${result.statistics.critical}\n`;
  report += `High:             ${result.statistics.high}\n`;
  report += `Medium:           ${result.statistics.medium}\n`;
  report += `Low:              ${result.statistics.low}\n`;
  report += `Info:             ${result.statistics.info}\n\n`;

  // EthTrust Level Details
  const ethTrustDef = getEthTrustLevelDefinition(result.ethTrustLevel);
  report += 'ETHTRUST SECURITY ASSESSMENT\n';
  report += '───────────────────────────────────────────────────────────\n';
  report += `Level:            ${ethTrustDef.level} - ${ethTrustDef.name}\n`;
  report += `Risk:             ${ethTrustDef.risk}\n`;
  report += `Description:      ${ethTrustDef.description}\n`;
  report += `Recommendation:   ${ethTrustDef.recommendation}\n\n`;

  // SCSVS Compliance
  report += 'SCSVS v2 COMPLIANCE\n';
  report += '───────────────────────────────────────────────────────────\n';
  report += `Compliance Score: ${result.scsvCompliance.percentage}%\n`;
  report += `Passed:           ${result.scsvCompliance.passed}\n`;
  report += `Failed:           ${result.scsvCompliance.failed}\n\n`;

  // Vulnerabilities Details
  if (result.vulnerabilities.length > 0) {
    report += 'DETECTED VULNERABILITIES\n';
    report += '═══════════════════════════════════════════════════════════\n\n';

    result.vulnerabilities.forEach((vuln, index) => {
      report += `${index + 1}. ${vuln.name}\n`;
      report += '───────────────────────────────────────────────────────────\n';
      report += `Severity:         ${vuln.severity}\n`;
      report += `Type:             ${vuln.type}\n`;
      report += `SWC ID:           ${vuln.swcId}\n`;
      report += `Line Number:      ${vuln.lineNumber}\n`;
      report += `Detection:        ${vuln.detectionMethod}\n`;
      report += `Confidence:       ${vuln.confidence}\n\n`;
      report += `Description:\n${vuln.description}\n\n`;
      report += `Exploitation Scenario:\n${vuln.exploitationScenario}\n\n`;
      report += `Recommendation:\n${vuln.recommendation}\n\n`;
      
      if (vuln.codeSnippet) {
        report += `Code Snippet:\n${vuln.codeSnippet}\n\n`;
      }
      
      if (vuln.references.length > 0) {
        report += 'References:\n';
        vuln.references.forEach(ref => {
          report += `  - ${ref}\n`;
        });
        report += '\n';
      }
      report += '\n';
    });
  }

  // Recommendations
  if (result.recommendations.length > 0) {
    report += 'RECOMMENDATIONS\n';
    report += '═══════════════════════════════════════════════════════════\n';
    result.recommendations.forEach((rec, index) => {
      report += `${index + 1}. ${rec}\n`;
    });
    report += '\n';
  }

  // Footer
  report += '───────────────────────────────────────────────────────────\n';
  report += 'Generated by SmartAudit AI\n';
  report += `Report generated on: ${new Date().toLocaleString()}\n`;
  report += '═══════════════════════════════════════════════════════════\n';

  // Create and download the file
  const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  const baseFileName = result.fileName.replace(/\.[^/.]+$/, '');
  link.download = `${baseFileName}-security-report.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}
