// PDF Report Generator - Using Professional Text Audit Format

import jsPDF from 'jspdf';
import { AnalysisResult } from '@/types';
import { generateTextAuditReport } from './text-audit-report-generator';

export function generatePDFReport(result: AnalysisResult): void {
  // Generate the professional text audit report
  const textReport = generateTextAuditReport(result);

  // Create PDF with the text report
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const maxWidth = pageWidth - margin * 2;
  let yPosition = margin;

  // Set default font
  doc.setFont('courier');
  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);

  // Split text into lines for proper pagination
  const lines = textReport.split('\n');

  lines.forEach((line: string) => {
    // Check if we need a new page
    if (yPosition > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
    }

    // Handle special characters and formatting
    const displayLine = line.replace(/[↑↓←→]/g, ''); // Remove directional arrows if any

    // Split long lines if needed
    const wrappedLines = doc.splitTextToSize(displayLine, maxWidth);

    wrappedLines.forEach((wrappedLine: string) => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }

      // Set text color based on line content for better readability
      if (displayLine.includes('═')) {
        doc.setTextColor(60, 60, 60);
      } else if (
        displayLine.includes('Critical') ||
        displayLine.includes('CRITICAL')
      ) {
        doc.setTextColor(220, 38, 38);
      } else if (displayLine.includes('High') || displayLine.includes('HIGH')) {
        doc.setTextColor(245, 158, 11);
      } else {
        doc.setTextColor(0, 0, 0);
      }

      doc.text(wrappedLine, margin, yPosition);
      yPosition += 3.5;
    });
  });

  // Add footer to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(
      `Generated by SmartAudit | Page ${i} of ${totalPages} | ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' },
    );
  }

  // Save the PDF
  const timestamp = new Date().toISOString().split('T')[0];
  const fileName = `security-report-${result.fileName.replace(/\.[^/.]+$/, '')}-${timestamp}.pdf`;
  doc.save(fileName);
}
